Myblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from blog.views import home,about,contact,dashboard,signup,ulogin,ulogout,add_post,update,deleted,details

urlpatterns = [
    path('admin/', admin.site.urls),
     path('',home,name='home'),
    path('about/',about,name='about'),
    path('contact/',contact,name='contact'),
    path('dashboard/',dashboard,name='dashboard'),
    path('sign/',signup,name='signup'),
    path('login/',ulogin,name='login'),
    path('logout/',ulogout,name='logout'),
    path('addpost/',add_post,name="addpost"),
    path('update/<int:id>/',update,name='update'),
    path('delete/<int:id>/',deleted,name='delete'),
    path('details/<int:id>/',details,name='detail'),

    
]+  static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=100)
    content=models.CharField( max_length=100000)
    author=models.CharField(max_length=100)
    photo=models.ImageField(upload_to='myimg')
    publication_date=models.DateTimeField(auto_now_add=True)

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect
from.form import Signup,Login,Adam
from.models import Post



#Home
def home(request):
    posts=Post.objects.all()
    return render(request,'blog/home.html',{'posts':posts})


#About
def about(request):
    return render(request,'blog/about.html')

#contact
def contact(request):
    return render(request,'blog/contact.html')

#Dashboard
def dashboard(request):
    if request.user.is_authenticated:
        posts=Post.objects.all()
        user=request.user
        full_name=user.get_full_name()
        return render(request,'blog/dashboard.html',{'posts':posts,'full':full_name})
    else:
        return HttpResponseRedirect('/login/')

#signup
def signup(request):
    if request.method=="POST":
        fm=Signup(request.POST)
        if fm.is_valid():
            fm.save()
    else:
        fm=Signup()
    return render(request,'blog/signup.html',{'form':fm})

#login
def ulogin(request):
    if not request.user.is_authenticated:
        if request.method=='POST':
            fm=Login(request=request,data=request.POST)
            if fm.is_valid():
                uname=fm.cleaned_data['username']
                upass=fm.cleaned_data['password']
                user=authenticate(username=uname,password=upass)
                if user is not None:
                    login(request,user)
                    return HttpResponseRedirect('/dashboard/')
        else:
            fm=Login()
        return render(request,'blog/login.html',{'form':fm})
    else:
        return HttpResponseRedirect('/dashboard/')

#logout
def ulogout(request):
    logout(request)
    
    return HttpResponseRedirect('/')


#Addpost 
def add_post(request):
    if request.user.is_authenticated:
        if request.method=='POST':
            fm=Adam(request.POST,request.FILES)
            if fm.is_valid():
                fm.save()
                fm=Adam()
        else:
            fm=Adam()
        return render(request,'blog/addpost.html' ,{'form':fm})
    else:
        return HttpResponseRedirect('/login/')
    
def update(request,id):
    if request.user.is_authenticated:
        if request.method=='POST':
            pi=Post.objects.get(pk=id)
            fm=Adam(request.POST,instance=pi)
            if fm.is_valid():
                fm.save()
        else:
            pi=Post.objects.get(pk=id)
            fm=Adam(instance=pi)
        return render (request,'blog/update.html',{'form':fm})
    else:
        return HttpResponseRedirect('/login/')
    
def deleted(request,id):
    if request.user.is_authenticated:
        if request.method=='POST':
            pi=Post.objects.get(pk=id)
            pi.delete()
            return HttpResponseRedirect('/dashboard/')
    else:
        return HttpResponseRedirect('/login/')


def details(request,id):
    if request.user.is_authenticated:
       obj=get_object_or_404(Post,id=id)
       return render(request,'blog/detail.html',{'obj':obj})
    else:
        return HttpResponseRedirect('/login/')
    
    

blog/templates/blog/about.html
{% extends "blog/base.html" %}
 {% load static %}
 {% block title%}
     About
 {% endblock title %}
 {% block content %}
 <div class="col-sm-10">
 <h2 class="my-5 offset-2">About page</h2>
      <p class="offset-2" style="background-color:pink">Blogs are a type of regularly updated websites that provide insight into a certain topic. The word blog is a combined version of the words “web” and “log.” At their inception, blogs were simply an online diary where people could keep a log about their daily lives on the web. They have since morphed into an essential forum for individuals and businesses alike to share information and updates. In fact, many people even make money blogging as professional full-time bloggers.</p>

 </div>
 {% endblock content %}

blog/templates/blog/addpost.html
{% extends "blog/base.html" %}
 {% load static %}
 {% block title%}
    Addpost
 {% endblock title %}
 {% block content %}
 <div class="col-sm-10">
 <h2 class="my-5">Addpost</h2>
 <form action="" method="POST", enctype="multipart/form-data">
    {% csrf_token %}
   {{form.as_p}}
   
   
    <input type="submit" class='btn btn-primary' value="update">
    <a href="{% url 'dashboard' %}" class="btn btn-primary">cancel</a>
 </form>
 {% endblock content %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}{% endblock title%}</title>
    <link rel="stylesheet" href="{% static 'css/all.css' %}"></link>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"></link>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"></link>
</head>
<body>
    
        <div class="container-fluid bg-warning">
            {% include 'blog/navbar.html' %}
        </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
            {% block msg %}
            {% endblock msg %}
            </div>
        </div>
        <div class='row'>
            {% block side %}
            {% endblock side %}

            {% block content %}
            {% endblock content %}
        </div>
    </div>












    <script src="{% static 'blog/js/all.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.js' %}"></script>
    <script src="{% static 'blog/js/jquery.js' %}"></script>
    <script src="{% static 'blog/js/popper.js' %}"></script>
</body>
</html>

blog/templates/blog/contact.html
{% extends "blog/base.html" %}
{% load static %}
{% block title%}
    contact
{% endblock title %}
{% block content %}
<div class="col-sm-8">
<h3> contact page </h3>

    <div class="mb-3">
      <label for="" class="form-label">Name</label>
      <input type="text" name="" id="" class="form-control" >
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Email</label>
        <input type="text" name="" id="" class="form-control" >
      </div>
      <div class="mb-3">
        <label for="" class="form-label">Address</label>
        <input type="text" name="" id="" class="form-control" >
      </div>
      <div class="mb-3">
        <label for="Messages" class="form-label">Messages</label>
        <textarea id="Messages" class="form-control"  row="3"></textarea>
      </div>
      <input class="btn btn-primary" type="submit" value="submit">
</div>
{% endblock content %}

blog/templates/blog/dashboard.html
{% extends "blog/base.html" %}
 {% load static %}
 {% block title%}
     Dashboard
 {% endblock title %}
          {% block msg %}
                {% if messages %}
                {% for message in messages %}
                <span {% if message.tag %} class="alert-{{message}}" {% endif %} >
                    {{message}}</span>
                {% endfor %}
                {% endif %}
            {% endblock msg %}

          {% block side%}
          <div class="col-2 mt-5">
              <h3 class="text-capitalize">{{user}}</h3>
          </div>

          {%endblock side%}
 {% block content %}
 <div class="col-sm-10">
 <h2 class="my-5">Dashboard</h2>
 <a href="{% url 'addpost' %}" class="btn btn-warning">Add post</a>
 <h4 class="text-center alert alert-primary"> Show Blog information</h4>
    {% if posts %}
    <table class="table table-hover">
        <thead>
          <tr>
            <th>id </th>
            <th>Title</th>
            <th>Description</th>
            <th>Author</th>
            <th>img</th>
            <th>Date</th>
            <th>Action</th>
          </tr>
        </thead>
        {% for st in posts %}
        <tbody>
          <tr>
            <th scope="row">{{st.id}}</th>
            <td>{{st.title}}</td>
            <td>{{st.content}}</td>
            <td>{{st.author}}</td>
            <td>{{st.photo}}</td>
            <td>{{st.publication_date}}</td>
            <td><a href="{% url 'update' st.id %}" class="btn btn-success">Edit</a>
                {% if perms.miniblog.delete_post %}
                <form action="{% url 'delete' st.id %}" method="POST" novalidate class="d-inline">
                 {%csrf_token%}
                <input type="submit" value="Delete" class="btn btn-danger">
                </form>
            {% endif %}
               </td>
          </tr>
        </tbody>
        {% endfor %}
        </table>
    {% else %}
    <h4 class="text-center alert alert-warning">No records</h4>

    {%endif %}

   
 </div>
 {% endblock content %}

blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% block title %}
    {{post.title}}
{% endblock title %}

{% block content %}
<div class="mt-4">
<h2 class="text-center">{{obj.title}}</h2><br>
<div class="col-4 offset-3">
<img src="{{obj.photo.url}}" height="200px" width="500" alt="MY IMG"></img><br><br>
</div>
 <p>{{obj.content}}</p>
<div class="col">
    <span>Author :</span><strong class="fw-bold">{{obj.author}}</strong>
</div>
<div class="col">
<span>Date :</span><small class="fw-bold">{{obj.publication_date}}</small>
</div>

</div>
{% endblock content %}

blog/templates/blog/home.html
 {% extends "blog/base.html" %}
 {% load static %}
 {% block title%}
     HOME
 {% endblock title %}
 {% block content %}
 <div class="col-fluid">
 <h2 class="my-2 bg-primary text-center">Read Our Blog</h2><br><br>
 <div class="container">
  <div class="row">
   {% for post in posts %}
   <div class="card mx-2 mt-2" style="width: 18rem;">
    <a href="{% url 'detail' post.id %}"><img class="card-img-top" src="{{post.photo.url}}" alt="Card image cap"></a>
    <div class="card-body">
      <h5 class="card-title">{{post.title}}</h5>
      <strong>Author:</strong>{{post.author}}<br>
      <small><strong>Date:</strong>{{post.publication_date}}</small><br>
      <a href="{% url 'detail' post.id %}" class="btn btn-primary">Read more</a>
    </div>

    
  </div>
    {% endfor %}
</div>
</div>
 </div>
 {% endblock content %}

blog/templates/blog/login.html
{% extends "blog/base.html" %}
 {% load static %}
 {% block title%}
     Log_In
 {% endblock title %}

 {% block content %}
 <div class="col-5 offset-3 mt-5">
    <div class="card">
        <div class="card-body">
 <h2 class="my-5 text-center">login</h2>
           
                <div class='col'>
                    <form action="" method="POST" novalidate>
                         {% csrf_token %}
                    {% for fm in form %}
                    {{fm.label_tag }}{{fm}} <small class="text-danger">{{fm.errors|striptags}}</small><br>
                    {% endfor %}
                    <input type="submit" value="login" class="btn btn-primary">
                    {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="alert alert-danger">{{error}}</p>
                    {% endfor %}
                {% endif %}

                    
                    </form>
                </div>
            </div>
        </div>
 </div>
 {% endblock content %}

blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg bg-warning">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
          <a class="nav-link" href="{% url 'about' %}">About</a>
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          {% if request.user.is_authenticated %}
          <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
          <a class="nav-link" href="{% url 'logout' %}">Log_Out</a>
          {% else %}
          <a class="nav-link" href="{% url 'signup' %}">Sign_up</a>
          <a class="nav-link" href="{% url 'login' %}">Log_In</a>
          {% endif %}
         
         
        </div>
      </div>
    </div>
  </nav>

blog/templates/blog/signup.html
{% extends "blog/base.html" %}
 {% load static %}
 {% block title%}
     signup
 {% endblock title %}

 {% block content %}
 <div class="col-6 offset-3 mt-1">
    <div class="card">
        <div class="card-body">
 <h2 class="my-5 text-center" style="text-decoration:underline;">signup</h2>
            
                <div class='col-9 offset-1'>
        <form action="" method="POST" novalidate>
            {% csrf_token%}
            {% for fm in form %}
            {{fm.label_tag }}{{fm}} <small class="text-danger">{{fm.errors|striptags}}</small><br>
            {% endfor %}
            <input type="submit" valu="submit" class="btn btn-primary">
            {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <span class="text-danger">{{error}}</span>
                    {% endfor %}
                {% endif %}
            
        </form>
    </div>

</div>
</div>
 </div>
 {% endblock content %}

blog/templates/blog/update.html
{% extends "blog/base.html" %}
 {% load static %}
 {% block title%}
     Update
 {% endblock title %}
 {% block content %}
 <div class="col-sm-10">
 <h2 class="my-5">Update Page</h2>
 <form action="" method="POST",novalidate>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class='btn btn-primary' value="Update">
    <a href="{% url 'dashboard' %}" class="btn btn-primary">Cancle</a>
 </form>
 {% endblock content %}